services:
  postgres:
    image: "postgres:16.2"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tarbox_user
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=tarbox
    ports:
      - "5455:5432"
