version: '3'
services:
  tarboxdb:
    image: "postgres:16.2"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tarbox_user
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=tarbox
    ports:
      - "5455:5432"
    networks:
      - tarbox-network
  server:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - tarbox-network
networks:
  tarbox-network:
    driver: bridge