name: Deploy to AWS EC2

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Server Tests
        run: mvn test

      - name: Stop Spring Boot application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker container stop TarboxServer

      - name: Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git pull origin release
            cd ./tarbox
            docker build . --tag tarbox_server:version --no-cache

      - name: Start Spring Boot application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker run -e "SPRING_PROFILES_ACTIVE=prod" --name TarboxServer -p 80:80 -d tarbox_server:version